name: pack_repository
description: The repo that handles pack question
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^4.19.2
  cloud_firestore: ^4.17.0
  rxdart: ^0.27.7
  gallery_picker: ^0.4.8
  firebase_storage: ^11.7.4
  file_picker: ^8.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
