// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPWUN6FuYaYHeq_xjI4xcAeSe-pdUI7M',
    appId: '1:963048559821:web:e73a04b5904dbd11a58584',
    messagingSenderId: '963048559821',
    projectId: 'teach-flutter-2',
    authDomain: 'teach-flutter-2.firebaseapp.com',
    storageBucket: 'teach-flutter-2.appspot.com',
    measurementId: 'G-Y0RJTLNZE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4ZIYWO70ePeatsL9XVtSMAQW0SNd6uBs',
    appId: '1:963048559821:android:34f8bf54662bae41a58584',
    messagingSenderId: '963048559821',
    projectId: 'teach-flutter-2',
    storageBucket: 'teach-flutter-2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT_v0k0YsbDHCamaWKc4fHUhYmIFDBLgo',
    appId: '1:963048559821:ios:46ef09babf419bcda58584',
    messagingSenderId: '963048559821',
    projectId: 'teach-flutter-2',
    storageBucket: 'teach-flutter-2.appspot.com',
    iosBundleId: 'com.example.flutterAppTeach2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT_v0k0YsbDHCamaWKc4fHUhYmIFDBLgo',
    appId: '1:963048559821:ios:46ef09babf419bcda58584',
    messagingSenderId: '963048559821',
    projectId: 'teach-flutter-2',
    storageBucket: 'teach-flutter-2.appspot.com',
    iosBundleId: 'com.example.flutterAppTeach2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKPWUN6FuYaYHeq_xjI4xcAeSe-pdUI7M',
    appId: '1:963048559821:web:7e338cfea6d2c3eea58584',
    messagingSenderId: '963048559821',
    projectId: 'teach-flutter-2',
    authDomain: 'teach-flutter-2.firebaseapp.com',
    storageBucket: 'teach-flutter-2.appspot.com',
    measurementId: 'G-NQXFF0BQFS',
  );
}
